### ISSUE TITLE
1.9.0 is broken

### ISSUE THREAD

**Issue by andy-viv** [mtennoe/swagger-typescript-codegen#59]
Thanks for the great library, we are using it well in our projects.

Currently (v1.9.0) for the simplest case, the lintCode.js file is breaking generation. It seems as though it is attempting to lint the client as a javascript file instead of a typesript file. Here is a minimal reproduction of the error:

https://gist.github.com/andy-viv/8004ff39407f6d2fa14c8c4d14d36a2f

The error that occurs:

```
            throw new Error(`${error.reason} in ${error.evidence} (${error.code})`);
            ^

Error: Unexpected 'type'. in export type RequestHeaders = { (E024)
    at lint.errors.forEach (/Users/andrew.perlitch/repos/stg-test/node_modules/swagger-typescript-codegen/lib/enhance/lintCode.js:22:19)
    at Array.forEach (<anonymous>)
    at Object.lintCode (/Users/andrew.perlitch/repos/stg-test/node_modules/swagger-typescript-codegen/lib/enhance/lintCode.js:20:17)
    at Object.enhanceCode (/Users/andrew.perlitch/repos/stg-test/node_modules/swagger-typescript-codegen/lib/enhance/index.js:7:20)
    at Object.getTypescriptCode (/Users/andrew.perlitch/repos/stg-test/node_modules/swagger-typescript-codegen/lib/codegen.js:18:26)
    at Object.<anonymous> (/Users/andrew.perlitch/repos/stg-test/generate.js:6:28)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
```

For now I am locking the version of swagger-typescript-codegen in my package.json to 1.8.1.

Are tests run on PR? I took the spec.json in the gist above directly from [the test fixtures](https://github.com/mtennoe/swagger-typescript-codegen/blob/master/tests/apis/ref.json) in this repo.

Also, I am noticing a strange discrepancy between npm versions and the releases on github. Perhaps check that you are tagging/releasing appropriately.

Regards

**Comment by mtennoe** [comment]
Thanks for reporting! This is strange, will take a look after the weekend.
Tests are run on PRs, but this might not be covered.

Re. versioning - I did some testing of publishing via Github and travis, but decided on not using that yet, which is probably why the versioning is inconsistent. I deleted the github tags now to clean it up. 1.9.0 is the correct latest version

**Comment by mtennoe** [comment]
We were discussing the removal of ESLint/jshint in the internal typescript rewrite, as it doesn't really make any sense since this project is only generating TS code anyway. I have created a PR for removing JS linting from the pipeline (#60), which fixes the issue.

We should look into adding a TSLint option ofc, but that can be done later

**Comment by mtennoe** [comment]
@andy-viv 1.9.2 published with the fix

**Comment by andy-viv** [comment]
Thanks @mtennoe, testing now!
